In [1]:
import func
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
chunk_size = 100000  # 每次处理 10 万行
#输出内容
op_path='standardnew'

import pandas as pd

In [2]:

# ---------- 工具：任意格式 -> YYYYMM(Int64) ----------
def to_yyyymm(series: pd.Series) -> pd.Series:
    s = series.astype(str).str.strip()

    # 情况A：已经是 6 位 YYYYMM
    mask6 = s.str.fullmatch(r"\d{6}", na=False)

    out = pd.Series([pd.NA] * len(s), index=s.index, dtype="Int64")

    # 6位直接转
    out.loc[mask6] = s.loc[mask6].astype("Int64")

    # 情况B：YYYY-MM / YYYY-MM-DD / datetime 等
    dt = pd.to_datetime(s.loc[~mask6], errors="coerce")
    out.loc[~mask6] = (dt.dt.year * 100 + dt.dt.month).astype("Int64")

    return out

In [3]:
df_standard=func.read_csv('CHN24/all_predictors.csv')

0    000002
1    000002
2    000002
3    000002
4    000002
Name: STKCD, dtype: str

CSV 数据预览：
    STKCD        date  mom6m  mom12m  mom36m     mom1m  chmom      turn  IPO  \
0  000002  1991-03-31    NaN     NaN     NaN       NaN    NaN       NaN  1.0
1  000002  1991-04-30    NaN     NaN     NaN  0.039972    NaN       NaN  1.0
2  000002  1991-05-31    NaN     NaN     NaN -0.126574    NaN  0.018804  1.0
3  000002  1991-06-30    NaN     NaN     NaN -0.116085    NaN  0.013065  1.0
4  000002  1991-07-31    NaN     NaN     NaN -0.030901    NaN  0.021065  1.0

   indmom  ...  VAHU  Hn  LFE  Adm  gAd  Ol  AnA  ReA  Tan  INA
0     NaN  ...   NaN NaN  NaN  NaN  NaN NaN  NaN  NaN  NaN  NaN
1     NaN  ...   NaN NaN  NaN  NaN  NaN NaN  NaN  NaN  NaN  NaN
2     NaN  ...   NaN NaN  NaN  NaN  NaN NaN  NaN  NaN  NaN  NaN
3     NaN  ...   NaN NaN  NaN  NaN  NaN NaN  NaN  NaN  NaN  NaN
4     NaN  ...   NaN NaN  NaN  NaN  NaN NaN  NaN  NaN  NaN  NaN

[5 rows x 114 columns]

In [4]:
df_standard['TRDMNT']=to_yyyymm(df_standard['date'])

/var/folders/nh/lgd9jvtn039crv3s33xn1xq40000gn/T/ipykernel_49104/2469092916.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_standard['TRDMNT']=to_yyyymm(df_standard['date'])

In [5]:
df_company=pd.read_csv('CHN24/cn_company_profile.csv', encoding='utf-8')

In [6]:
df_company.head()

,STKCD,LISTDT,CUNTRYCD,CONME_EN,INDCD,NINDCD,NNINDCD,INDCDZX,ESTBDT,PROVINCECODE,...,NSHRIPO,PARVCUR,IPODT,PARVAL,SCTCD,STATCO,CRCD,STATDT,COMMNT,MARKETTYPE
0,1,1991/4/3,10,"Ping An Bank Co., Ltd.",1.0,I01,J66,J66,1987/12/22,440000,...,350.0,CNY,1989/3/10,20.0,2,A,NaN,2025/4/14,NaN,4
1,2,1991/1/29,10,"China Vanke Co., Ltd.",3.0,J,K70,K70,1984/5/30,440000,...,28000.0,CNY,1988/12/28,1.0,2,A,NaN,2025/4/14,2202.0,4
2,3,1991/7/3,10,"Gintian Industry (Group) Co., Ltd.",4.0,M,S90,S91,1982/1/1,440000,...,452.0,CNY,1989/2/28,1.0,2,D,NaN,2002/6/14,NaN,4
3,4,1991/1/14,10,Shenzhen Guohua Network Security Technology Co...,2.0,G87,I65,I65,1986/5/5,440000,...,12500.0,CNY,1989/12/23,1.0,2,A,NaN,2025/4/30,NaN,4
4,5,1990/12/10,10,Shenzhen Fountain Corporation,2.0,K99,N77,N77,1987/1/1,440000,...,44339.0,CNY,1990/3/3,1.0,2,D,NaN,2024/4/26,NaN,4

In [7]:
df_standard.head(1000)

,STKCD,date,mom6m,mom12m,mom36m,mom1m,chmom,turn,IPO,indmom,...,Hn,LFE,Adm,gAd,Ol,AnA,ReA,Tan,INA,TRDMNT
0,000002,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199103
1,000002,1991-04-30,NaN,NaN,NaN,0.039972,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199104
2,000002,1991-05-31,NaN,NaN,NaN,-0.126574,NaN,0.018804,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199105
3,000002,1991-06-30,NaN,NaN,NaN,-0.116085,NaN,0.013065,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199106
4,000002,1991-07-31,NaN,NaN,NaN,-0.030901,NaN,0.021065,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,000005,1998-08-31,0.340660,-0.137574,3.786693,-0.136066,0.514957,1.712642,0.0,0.349471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199808
996,000005,1998-09-30,0.290086,0.250183,1.897468,-0.045541,0.262265,0.730342,0.0,0.351056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199809
997,000005,1998-10-31,0.040331,0.203350,1.954653,0.021371,-0.094136,0.699032,0.0,0.442837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199810
998,000005,1998-11-30,-0.057341,0.443117,1.674471,0.008759,-0.579984,0.912539,0.0,0.264408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199811
999,000005,1998-12-31,-0.181281,0.083071,2.765037,-0.033285,-0.531417,1.046593,0.0,0.296843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199812

In [8]:
#将df_company的STKCD补充前导0，使其成为6位字符串
df_company['STKCD'] = df_company['STKCD'].astype(str).str.zfill(6)

In [9]:
df_company_merge = df_company[['STKCD',  'INDCDZX']].copy()

In [10]:
#将df_company的
df_standard = pd.merge(
    df_standard,
    df_company_merge,
    on=['STKCD'],
    how='left',
    validate='many_to_one'  # 行业代码在同一股票-月份下应唯一
)

In [11]:
df_ret=pd.read_csv('CHN24/monret.csv', encoding='utf-8')

In [12]:
df_ret_merge = df_ret[['STKCD', 'TRDMNT', 'MRETWD']].copy()

In [13]:
df_ret_merge['TRDMNT']=to_yyyymm(df_ret_merge['TRDMNT'])

In [14]:
df_ret_merge.head()

   STKCD  TRDMNT    MRETWD
0      1  199104       NaN
1      1  199105 -0.122253
2      1  199106 -0.113459
3      1  199107 -0.130921
4      1  199108 -0.411588

In [15]:
df_ret_merge['STKCD'] = df_ret_merge['STKCD'].astype(str).str.zfill(6)

In [16]:
df_standard = pd.merge(
    df_standard,
    df_ret_merge,
    on=['STKCD','TRDMNT'],
    how='left',
    validate='one_to_one'  # 行业代码在同一股票-月份下应唯一
)

In [17]:
df_standard.head()

,STKCD,date,mom6m,mom12m,mom36m,mom1m,chmom,turn,IPO,indmom,...,Adm,gAd,Ol,AnA,ReA,Tan,INA,TRDMNT,INDCDZX,MRETWD
0,000002,1991-03-31,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199103,K70,-0.126574
1,000002,1991-04-30,NaN,NaN,NaN,0.039972,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199104,K70,-0.116085
2,000002,1991-05-31,NaN,NaN,NaN,-0.126574,NaN,0.018804,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199105,K70,-0.030901
3,000002,1991-06-30,NaN,NaN,NaN,-0.116085,NaN,0.013065,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199106,K70,-0.303809
4,000002,1991-07-31,NaN,NaN,NaN,-0.030901,NaN,0.021065,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199107,K70,-0.061069

In [18]:

# ---------- 定义起止时间（YYYYMM int） ----------
start_month = 200001
end_month   = 202412
# 日期筛选
df_csv_filtered = df_standard.loc[
    (df_standard["TRDMNT"] >= start_month) & (df_standard["TRDMNT"] <= end_month)
].copy()

print("before/after:", len(df_standard), len(df_csv_filtered))
print("min/max after:", df_csv_filtered["TRDMNT"].min(), df_csv_filtered["TRDMNT"].max())

before/after: 740845 698913
min/max after: 200001 202412

In [19]:
#把MRETWD列重命名为RET
df_csv_filtered.rename(columns={'MRETWD': 'RET'}, inplace=True)

In [20]:
#保存df_standard
import os
#df_csv_filtered.to_csv(os.path.join(op_path, "prepared.csv"), index=False)

In [21]:
df_csv_filtered.head()

,STKCD,date,mom6m,mom12m,mom36m,mom1m,chmom,turn,IPO,indmom,...,Adm,gAd,Ol,AnA,ReA,Tan,INA,TRDMNT,INDCDZX,RET
106,000002,2000-01-31,-0.041354,0.182541,-0.084426,0.141829,-0.138944,2.067810,0.0,0.168533,...,NaN,NaN,0.475384,NaN,NaN,NaN,0.0,200001,K70,0.161126
107,000002,2000-02-29,-0.136440,0.459048,0.208242,-0.122412,-0.931725,2.328343,0.0,0.277902,...,NaN,NaN,0.475384,NaN,NaN,NaN,0.0,200002,K70,0.405687
108,000002,2000-03-31,-0.163550,0.376680,0.052413,0.161126,-0.674637,3.386074,0.0,0.222441,...,NaN,NaN,0.475384,NaN,NaN,NaN,0.0,200003,K70,-0.144302
109,000002,2000-04-30,-0.009539,0.633882,0.029622,0.405687,-0.257339,6.743252,0.0,0.489288,...,NaN,NaN,0.475384,NaN,NaN,NaN,0.0,200004,K70,-0.016548
110,000002,2000-05-31,0.499882,1.249856,-0.181686,-0.144302,-0.216577,10.224872,0.0,0.546886,...,NaN,NaN,0.475384,NaN,NaN,NaN,0.0,200005,K70,-0.047276

# 标准化

In [22]:
#在df_csv_filtered中，新建一列size_raw,值为size列的原始值
df_csv_filtered['size_raw'] = df_csv_filtered['size']

In [23]:
import numpy as np
import pandas as pd

# 1️⃣ 明确哪些列不能动
exclude_cols = [
    'RET', 'INDCDZX',
    'TRDMNT', 'STKCD', 'date','size'
]

# 2️⃣ 自动识别「因子列」
factor_cols = [
    c for c in df_csv_filtered.columns
    if c not in exclude_cols
    and pd.api.types.is_numeric_dtype(df_csv_filtered[c])
]

print("将被标准化的因子列数量:", len(factor_cols))

将被标准化的因子列数量: 112

In [24]:
df_csv_s=df_csv_filtered.copy()
# 3️⃣ 行业 × 月份 内做 z-score
df_csv_s[factor_cols] = (
    df_csv_filtered
    .groupby(['INDCDZX', 'TRDMNT'])[factor_cols]
    .transform(lambda x: (x - x.mean()) / x.std(ddof=0))
)
print("标准化完成！")
print(df_csv_s[factor_cols].head())

标准化完成！
        mom6m    mom12m    mom36m     mom1m     chmom      turn       IPO  \
106 -1.042180  0.165599 -0.470788  2.097052 -1.039057  0.280377 -0.361158
107 -0.210615  0.776803 -0.238338 -0.727790 -0.905743  0.708814 -0.380693
108 -0.269587  0.525622 -0.321605  0.146812 -0.712768  0.544172 -0.358569
109 -0.003622  0.349919 -0.172868  1.510853  0.146093  0.662261 -0.335673
110  0.913752  1.277721 -0.449543 -1.293463 -0.487082  0.528957 -0.309662

       indmom    maxret    retvol  ...  Hn  LFE  Adm  gAd        Ol  AnA  ReA  \
106 -0.113961  2.884048  3.657999  ... NaN  NaN  NaN  NaN  0.558387  NaN  NaN
107 -0.113228  0.058516  0.049987  ... NaN  NaN  NaN  NaN  0.558387  NaN  NaN
108  0.113228  1.878421  1.273929  ... NaN  NaN  NaN  NaN  0.558387  NaN  NaN
109 -0.113228  0.461684  0.245126  ... NaN  NaN  NaN  NaN  0.558387  NaN  NaN
110 -0.112509 -0.367885 -0.069059  ... NaN  NaN  NaN  NaN  0.558387  NaN  NaN

     Tan       INA  size_raw
106  NaN -0.693045  4.658447
107  NaN -0.693045  5.256671
108  NaN -0.693045  6.162150
109  NaN -0.693045  5.608948
110  NaN -0.693045  5.151797

[5 rows x 112 columns]

In [26]:
df_csv_s.head()

,STKCD,date,mom6m,mom12m,mom36m,mom1m,chmom,turn,IPO,indmom,...,Adm,gAd,Ol,AnA,ReA,Tan,INA,TRDMNT,INDCDZX,RET
106,000002,2000-01-31,-1.042180,0.165599,-0.470788,2.097052,-1.039057,0.280377,-0.361158,-0.113961,...,NaN,NaN,0.558387,NaN,NaN,NaN,-0.693045,200001,K70,0.161126
107,000002,2000-02-29,-0.210615,0.776803,-0.238338,-0.727790,-0.905743,0.708814,-0.380693,-0.113228,...,NaN,NaN,0.558387,NaN,NaN,NaN,-0.693045,200002,K70,0.405687
108,000002,2000-03-31,-0.269587,0.525622,-0.321605,0.146812,-0.712768,0.544172,-0.358569,0.113228,...,NaN,NaN,0.558387,NaN,NaN,NaN,-0.693045,200003,K70,-0.144302
109,000002,2000-04-30,-0.003622,0.349919,-0.172868,1.510853,0.146093,0.662261,-0.335673,-0.113228,...,NaN,NaN,0.558387,NaN,NaN,NaN,-0.693045,200004,K70,-0.016548
110,000002,2000-05-31,0.913752,1.277721,-0.449543,-1.293463,-0.487082,0.528957,-0.309662,-0.112509,...,NaN,NaN,0.558387,NaN,NaN,NaN,-0.693045,200005,K70,-0.047276

In [25]:
#保存df_standard
import os
df_csv_s.to_csv(os.path.join(op_path, "prepared_s.csv"), index=False)